version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8500:80"
    restart: unless-stopped
    # If you want a custom container name, uncomment below
    # container_name: home_singularity_web
